version: '2'
services:
  web:
    image: nginx:1.15-alpine
    restart: always
    ports:
    - "80:80"
    volumes:
    - /root/Angelina:/usr/share/nginx/html:ro
    - /root/Angelina/nginx.conf:/etc/nginx/nginx.conf:ro
    - /root/site:/etc/nginx/sites-enabled:ro
